const quizData2 = [
    {
        question: "Yeni evliler kimliğini değiştirmeden oy kullanabilir mi?",
        a: "EVET",
        b: "HAYIR",
        correct: "a",
    },
    {
        question: "Sayım döküm işlemi bittikten sonra sandık sonuç tutanağıyla beraber ağzı mühürlü seçim torbasını ilçe seçim kuruluna kimler götürür?",
        a: "Yalnız Sandık Başkanı",
        b: "Parti Üyesi",
        c: "Okul Sorumlusu",
        d: "Sandık Başkanı ve 2 Sandık kurulu üyesi",
        correct: "d",
    },
    {
        question: "Sandığa gelen seçmenin oy kullanabilmesi için aşağıdakilerden hangisi kontrol edilmez?",
        a: "Gözlük kullanıp kullanmadığı",
        b: "Kimlikteki resim ile seçmenin uyup uymadığı",
        c: "Kimlikte TC kimlik numarası olup olmadığı",
        d: "Seçmenin sandığa ait seçmen listesinde olup olmadığı",
        correct: "a",
    },
    {
        question: "Sandık sonuç tutanağında aşağıdakilerden hangisi bulunur?",
        a: "Oy kullanan seçmenlerin toplam sayısı",
        b: "Artan oy ve pusulaların sayısı",
        c: "Geçersiz oy sayısı ve nedenleri",
        d: "Geçerli zarf ve pusula sayısı",
        e: "Hepsi",
        correct: "e",
    },
    {
        question: "Kazara lekelenmiş olan, katlama sebebiyle mührün başka alanlara bulaştığı, mührün çizgili bölüme taştığı, aynı adaya/partiye birden çok mühür basılan oy pusulaları geçerli midir?",
        a: "Geçerlidir",
        b: "Geçersizdir",
        correct: "a",
    },
    {
        question: "Aşağıdakilerden bilgilerden hangisi müşahitlere dair doğrudur?",
        a: "Oy verme sürecini izler ve sürecin şeffaf ve tarafsız olduğunu denetler",
        b: "Siyasi partiler ve adaylar müşahit görevlendirebilir",
        c: "Müşahitler sandık kurulunun 298 numaralı kanuna aykırı işleyişlerde şikayet ve itiraz etmeye yetkilidir. (Kanun 298, md. 110, md. 128, md.116)",
        d: "Hepsi",
        correct: "d",
    },
    {
        question: "Sandık Kurullarında aşağıdakilerden hangisi görev alabilir?",
        a: "Zabıta memuru veya amiri",
        b: "Doktorlar",
        c: "Askerler",
        d: "TBMM üyeleri",
        correct: "b",
    },
    {
        question: "Sayım ve döküm sırasında sandığın bulunduğu odanın kapısı kapatılır.",
        a: "Doğru",
        b: "Yanlış",
        correct: "b",
    },
    {
        question: "Sandık kurulunun yapması gereken ilk görev nedir?",
        a: "Oy bölgesini düzenlemek",
        b: "Mühürleme İşlemleri",
        c: "And İçme",
        d: "Sayım Yapmak",
        correct: "c",
    },
    {
        question: "Sayım sırasında zarfın içinden çıkan el ilanı, broşür, özel işaret veya amblem taşıyan kağıt veya madde çıkması halinde o zarftan çıkan pusula geçerli sayılır mı?",
        a: "EVET",
        b: "HAYIR",
        correct: "b",
    },
];