const quizData5 = [
    {
        question: "Hanife Teyze bir yıl önce felç geçirdiği için yatağa bağımlı halde yaşıyor. Kızı Hanife Teyze’nin oy kullanabilmesi için ne yapmalı?",
        a: "Oy kullanmamalı",
        b: "YSK’ya sağlık raporu ile Seyyar sandık başvurusu yapmalı",
        c: "Hanife Teyze’nin kızı onun yerine oy atmalı",
        d: "Hanife Teyze’yi ambulansla sandık başına götürmeli",
        correct: "b",
    },
    {
        question: "Sayım döküm süreçlerini oy verme alanında bulunan herkes izleyebilir.",
        a: "Doğru",
        b: "Yanlış",
        correct: "a",
    },
    {
        question: "Oy verme sürecinin bitiş saati tutanak defterine yazılır.",
        a: "Doğru",
        b: "Yanlış",
        correct: "a",
    },
    {
        question: "Sandık kurulu başkanının gelmemesi halinde sandık kurulu başkanlığını kim yapabilir?",
        a: "En çok oy alan parti temsilcisi",
        b: "Kura ile belirlenen kişi",
        c: "Memur Üye",
        d: "En eğitimli kişi",
        correct: "c",
    },
    {
        question: "Seçmen listelerinde kayıtlı olmayanlardan hangileri oy kullanabilir?",
        a: "Sandık kurulu başkanları ve üyeleri",
        b: "142 Belgesi olan kolluk güçleri",
        c: "İlçe seçim kurulu tarafından sandık kurulu üyelerini görev yerine ulaştırmak için görevlendirilmiş kişiler",
        d: "Hepsi",
        correct: "d",
    },
    {
        question: "Görme engelli ve Braille okuyamayan Yusuf Amca nasıl oy kullanabilir?",
        a: "Sandık başkanının yardımıyla",
        b: "Kolluk kuvveti desteği ile",
        c: "Parti üyesinin desteği ile",
        d: "Akrabası ya da herhangi bir seçmenin yardımıyla",
        correct: "d",
    },
    {
        question: "Oy pusulasında Tercih ya da Evet mührü çok küçük bir miktar diğer adayın bölgesine kaymış ancak kime oy verdiği belli. Sandık kurulu geçerli mi geçersiz mi tartışıyor. Hangisi doğru?",
        a: "Oy geçerlidir",
        b: "Oy geçersizdir",
        correct: "b",
    },
    {
        question: "Sandıktan çıkan zarfların sayımı en çok kaç kez yapılır?",
        a: "1",
        b: "2",
        c: "3",
        d: "4",
        correct: "c",
    },
    {
        question: "Sandık seçmen listesi seçim başlamadan sandık çevresinde seçmenlerin görüp inceleyebileceği bir yere asılır.",
        a: "Doğru",
        b: "Yanlış",
        correct: "a",
    },
    {
        question: "Sabah çıkan boş oy pusulaları üzerinde işaret var ise kabul edilir mi?",
        a: "Evet",
        b: "Hayır",
        correct: "b",
    }
];