const quizData6 = [
    {
        question: "Şikayet dilekçeleri kaç nüsha olarak hazırlanır?",
        a: "3",
        b: "2",
        c: "4",
        d: "5",
        correct: "b",
    },
    {
        question: "Seçim sırasında yaşlı bir amcaya kapalı oy verme kabinine kadar yürüme desteği verilmesi istenirse, bu karar kim tarafından alınır?",
        a: "Sandık başkanı",
        b: "Sandık kurulu çoğunluğu",
        c: "Müşahitler",
        d: "Yaşlı amca",
        correct: "b",
    },
    {
        prefix: "1) Huzurevinden gelen 80 yaşındaki amca\n2) 18 yaşında ilk oyunu kullanan genç\n3) Hamile bir kadın\n4) 40 yaşlarında öğretmen bayan,",
        question: "Aşağıdakiler oy kullanmak için sıraya girdiklerinde öncelik sırası nasıl olmalıdır?",
        a: "1-2-3-4",
        b: "3-4-2-1",
        c: "2-4-1-3",
        d: "3-1-2-4",
        correct: "d",
    },
    {
        question: "Sandık kurulu çoğunluğu hakkında aşağıdakilerden hangisi yanlıştır?",
        a: "Sandık başında, sandık kurulu üyelerinden biri veya birkaçı görevini yapmazsa yerine yedek üyelerden biri getirilir.",
        b: "Kurul üyeleri sayısı (başkan hariç) üçten aşağı düşerse ve yedek üye yok ise o seçim bölgesinde seçme yeterliliğine sahip, okur-yazar olanlar arasından başkanın seçeceği kimselerle tamamlanır.",
        c: "Sandık kurulu başkanı ve üç üyenin hazır bulunması halinde eksik üyeliklerin tamamlanması yoluna gidilmez.",
        d: "Yeminden gelen sonra gelen sandık kurulu üyesi seçim başladıktan sonra bile görevine başlar.",
        correct: "d",
    },
    {
        question: "Aşağıdaki pusulalardan hangisi geçerlidir?",
            a: "Adayların resimlerini içeren herhangi bir kağıt",
        b: "Hiçbir yerine mühür basılmamış pusula",
        c: "YSK filigranlı ve mühürlü pusulada tek bir adayı tercih ettiğini belirterek mühür basılan pusula",
        d: "Arkasında sandık mührü bulunmayan ama tek bir adayı tercih ettiğini belirterek mühür basılan pusula",
        correct: "c",
    },
    {
        question: "Leman Teyze seçim sonrasında kapıda asılı tutanağı görmeye sandığına gitti ve çöpte yanmış oy pusulaları gördü. Bu pusulalar neden yakılmıştır?",
            a: "Bir partinin pusulalarını oyları değiştirmek için yakmışlardır",
        b: "Sandık kurulu üyeleri ısınmak istemiştir",
        c: "Geçersiz oyları yakmışlardır",
        d: "Sandıktan çıkan zarf sayısı oy kullanan seçmen sayısından fazladır",
        correct: "d",
    },
    {
        question: "Bir sandıkta 8 tane parti müşahiti olabilir mi?",
            a: "Evet",
        b: "Hayır",
        correct: "b",
    },
    {
        question: "Oy pusulaları tüm parti müşahitleri ikna edilene ve sayılarda uzlaşana kadar sayılır mı?",
            a: "Evet",
        b: "Hayır",
        correct: "b",
    },
    {
        question: "Aşağıdakilerden hangisi olağan oy verme sürecinde sandık çevresinde bulunamaz?",
            a: "Müşahit",
        b: "Medya mensupları",
        c: "Milletvekilleri",
        d: "Kolluk kuvvetleri",
        correct: "d",
    },
    {
        prefix: "1) Kullanılmayan zarflar ve pusulalar paketlenir\n2) Tutanaklar doldurulur\n3) Sandıktan çıkan iki kere zarflar sayılır, geçerli-geçersiz zarflar ayrılır\n4) Zarflardan çıkan pusulalar sayılır, geçerli geçersiz oylar kontrol edilir\n5) Sayılan oylar ve zarflar paketlenir,",
            question: " Sayım işlerinin sırası aşağıdakilerden hangisidir?",
        a: " 3-2-1-4-5",
        b: " 1-3-5-4-2",
        c: " 1-3-4-2-5",
        d: " 3-1-4-2-5",
        correct: "c",
    },
    {
        question: "“Kolluk kuvvetleri sandık kurulunu denetler.” Doğru mu yanlış mı?",
            a: "Doğru",
        b: "Yanlış",
        correct: "b",
    },
    {
        question: "Yatağa bağımlı seçmenler nasıl oy kullanabilir?",
            a: "Belediyeden erişim desteği talep edilir",
        b: "Oy verme işlemi başkasına verdirtir",
        c: "Oy veremez",
        d: "YSK’ya seyyar sandık için başvuruda bulunur",
        correct: "d",
    },
    {
        question: "Dursun Bey sandık kurulunun verdiği mührün çalışıp çalışmadığını test etmek istedi ve zarfın üzerine 'Evet' mührünü bastı. Oy sayımı sırasında bu zarf geçerli sayılır mı?",
            a: "Evet, sonuçta seçim mührüdür.",
        b: "Hayır, zarf üzerinde YSK, İlçe Seçim Kurulu ve Sandık mühürü harici işaret bulunamaz.",
        correct: "b",
    },
    {
        question: "Sandık kurulu en az kaç kişi ile çalışmaya başlar?",
            a: "5",
        b: "4",
        c: "3",
        d: "2",
        correct: "b",
    },
    {
        question: "Sandık Kurulu tutanak defteri nedir?",
            a: "Sandık Kurulu’nun yaptığı tüm işlemlerin, tüm sayımların, şikayetlerin ve kararların kaydedildiği defterdir.",
        b: "Sandık Kurulunun not alması için koyulan defterdir.",
        c: "Oy sayımı sırasında oyların çetelesinin tutulduğu defterdir.",
        d: "Sandık başkanına verilen anı defteridir.",
        correct: "a",
    },
    {
        question: "Aşağıdakilerden hangisi seçim sürecinde şikayete yetkili değildir?",
            a: "Siyasi parti yetkilileri",
        b: "Seçme yeterliliğine sahip seçmen",
        c: "Adaylar",
        d: "Kolluk kuvvetleri",
        correct: "d",
    },
    {
        question: "Seyyar sandık kurulu ile ilişkilendirilen sandık kurulu, seyyar sandık gelmese bile saat 17:00 de sandığını açar?",
            a: "Doğru",
        b: "Yanlış",
        correct: "b",
    },
    {
        question: "Seyyar sandık görevlileri, seçmeni adresinde bulamazsa, tüm seçmenleri dolaştıktan sonra bu adreslere tekrar gider.",
            a: "Doğru",
        b: "Yanlış",
        correct: "b",
    },
    {
        question: " Sandık başında kardeşinize hangi partiye oy vermesi gerektiğini söylemekte sakınca yoktur.",
            a: "Doğru",
        b: "Yanlış",
        correct: "b",

    },
    {
        question: "Seyyar sandık nedir?",
            a: "Oy kullanmak için okula gelmek istemeyenler için gezici sandıktır",
        b: "Sandığın taşınma durumudur",
        c: "Hasta ve engeli sebebiyle sandıklara gidemeyen seçmene YSK tarafından sağlanan sandıktır",
        d: "Pazarlara kurulan sandıktır",
        correct: "c",
    },
];