const quizData4 = [
    {
        question: "Sandık kurulunda kim bulunamaz?",
        a: "Sandık Başkanı",
        b: "Memur Üye",
        c: "Cumhurbaşkanı adayı",
        d: "5 Siyasi Parti üyesi",
        correct: "c",
    },
    {
        question: "Sandık başkanı, sandık kurulunu 6:45 de oluşturdu ve yeminler edildi. Saat 6:55 de yeni bir sandık kurulu üyesi geldi. Sandık kurulu başkanı bu kişiyi alır?",
        a: "Doğru",
        b: "Yanlış",
        correct: "a",
    },
    {
        question: "Okuma yazma bilmeyen bir seçmen sorduğu ve istediği takdirde nasıl oy kullanmasına yardımcı olunabilir?",
        a: "Yanında gelen bir yakınının oy kullanma kabinine beraber gitmesiyle",
        b: "Sandık kurulundan biri beraberinde kabine giderek yardımcı olabilir",
        c: "Sandık kurulu başkanının kısaca hangi adayın nerede olduğunu ve mührü istediği adaya basması gerektiğini anlatmasıyla",
        d: "Müşahit veya etraftaki başka bir seçmenin yardımıyla",
        correct: "c",
    },
    {
        question: "Seçim sırasında Instagram'da oy kullanma farkındalığı yaratmak için fotoğraf çekilebilir mi?",
        a: "Evet",
        b: "Hayır",
        correct: "b",
    },
    {
        question: "“Zarflar ve Oy pusulaları mühürlenmelidir” cümlesi doğru mu yanlış mı?",
        a: "Doğru",
        b: "Yanlış",
        correct: "a",
    },
    {
        question: "Bir zarftan aynı adaya basılmış 3 ayrı Cumhurbaşkanlığı pusulası çıktı. Bu oy geçerli midir?",
        a: "Evet",
        b: "Hayır",
        correct: "b",
    },
    {
        question: "Oy kullanma sırasında kimler önceliklidir?",
        a: "Gebeler",
        b: "Hastalar",
        c: "Engelliler",
        d: "Hepsi",
        correct: "d",
    },
    {
        question: "Kazara lekelenmiş olan, katlama sebebiyle mührün başka alanlara bulaştığı, mührün çizgili bölüme taştığı, aynı adaya/partiye birden çok mühür basılan oy pusulaları geçerlidir?",
        a: "Doğru",
        b: "Yanlış",
        correct: "a",
    },
    {
        question: "Başkanın getirdiği seçim malzemeleri torbasından çıkan oy pusulaları ve zarfların sayısının seçmen listesinden az sayıda olması durumunda ne yapılır?",
        a: "Panik olunur",
        b: "YSK Bina Başkanından İlçe Seçim Kurulu ile çözülmesi istenir, gerekirse yan sınıflardan tamamlanır.",
        c: "Parti başkanlarına ulaşılır ve pusula ya da zarf getirmesi istenir.",
        d: "Zaten tüm seçmenler gelmez denerek devam edilir.",
        correct: "b",
    },
    {
        question: " Sayım sırasında oy pusulalarından birine itiraz yapıldı ve sayım döküm sürecini izleyen bireyler arasında fiziksel şiddet içeren bir kavga çıktı. Ne yapılması gerekir?",
        a: " Sandık kurulu başkanı seçimi durdurup müdahale eder.",
        b: " Seçmenler kolluk kuvvetlerinin müdahele etmesi için ihbar eder.",
        correct: "b",
    },
];