const quizData1 = [
    {
        question: "Saat 17:00 olduğu anda sırada seçmenlere varsa;",
        a: "Oy kullanamaz evlerine gönderilir",
        b: "Oy kullandırılmaz ama yardım etmeye çağırılır",
        c: "Sırada oldukları için başkan tarafından sayılır, kimlikleri toplanır ve oy kullandırılır",
        d: "Sandık kurulu toplanır ve oy kullanıp kullanamayacakları konusunda karar verilir",
        correct: "c",
    },
    {
        question: "Okuma yazma bilmeyen seçmen imza atmak yerine ne yapabilir?",
        a: "Başka bir seçmenden imza atmasını ister",
        b: "İmza atmaz",
        c: "Parmak basar",
        d: "Kalemle çizik atar",
        correct: "c",
    },
    {
        question: "Sandık Kurulu kaç kişiden oluşur?",
        a: "3",
        b: "4",
        c: "5",
        d: "7",
        correct: "d",
    },
    {
        question: "Şikayet ile itiraz aynı anlama mı gelir? ",
        a: "Evet",
        b: "Hayır",
        correct: "b",
    },
    {
        question: "Seçmen oyunu kullandıktan sonra sandık başında kalmaya devam edebilir.",
        a: "Evet",
        b: "Hayır",
        correct: "b",
    },
    {
        question: "Sandıktaki seçmen listesinde bulunan bütün seçmenler oylarını kullandıysa saat 17.00 beklenmeden sandıklar açılıp, sayım ve döküm işlemine geçilebilir.",
        a: "Doğru",
        b: "Yanlış",
        correct: "b",
    },
    {
        question: "142 numaralı görevlendirme belgesini seçmen ne yapmalıdır?",
        a: "Sandık kuruluna oy kullanmadan önce teslim eder",
        b: "Daha sonraki seçimler için saklar",
        correct: "a",
    },
    {
        question: "Sandık çevresinde telefonla konuşmak yasaktır?",
        a: "Doğru",
        b: "Yanlış",
        correct: "a",
    },
    {
        question: "Dursun Bey sandık kurulunun verdiği mührün çalışıp çalışmadığını test etmek istedi ve zarfın üzerine “Evet” mührünü bastı. Oy sayımı sırasında bu zarf geçerli sayılır mı?",
        a: "Evet, sonuçta seçim mührüdür.",
        b: "Hayır, zarf üzerinde YSK, İlçe Seçim Kurulu ve Sandık mühürü harici işaret bulunamaz.",
        correct: "b",
    },
    {
        question: "Seçmenler oy kullanmak için üzerinde TC Kimlik Numarası bulunan hangi tür kimlikleri ibraz edebilirler?",
        a: "Nüfus cüzdanı/ TC Kimlik Kartı",
        b: "Evlenme Cüzdanı",
        c: "Sürücü Belgesi",
        d: "Avukat, Noter, Askeri Kimlik Kartları",
        e: "Hepsi",
        correct: "e",
    },
];