const quizData3 = [
    {
        question: "Aşağıdakilerden hangisi sandık kurulunun görevidir?",
        a: "Oy verme işleri hakkındaki şikâyet ve itirazları inceleyip, kararı tutanak defterine işlemek",
        b: "Oyların sayım ve dökümü ile tutanakların düzenlenmesine ilişkin iş ve işlemler ve sandıkla ilgili kararları vermek",
        c: "Sandık kurullarının kararları, oyların sayımı ve dökümü ile tutanakların düzenlenmesine ilişkin iş ve işlemleri aleyhine yapılan itirazları ilçe seçim kuruluna göndermek",
        d: "Görev yaptığı sandığın seçmen listesinde kayıtlı olmayıp da, başka bir sandık seçmen listesinde kayıtlı olan kişilere ilçe seçim kurulundan aldıkları belgelere istinaden oy kullandırmak, oy kullandıkları seçmen listesinin sonuna yazmak, imzalarını almak ve belgeleri ilçe seçim kuruluna teslim etmek (Belge 142)",
        e: "Hepsi",
        correct: "e",
    },
    {
        question: "Sayım döküm cetveli ile ilgili aşağıdakilerden hangisi yanlıştır?",
        a: "Cetvel boş A4’e tutulur.",
        b: "Aday isimleri içeren QR kodlu cetveller YSK torbasından çıkar.",
        c: "En az 2 adet QR kodlu YSK’nın hazırladığı cetvel sandık kurulu tarafından işaretlenir.",
        d: "Tüm sandık üyeleri cetveli imzalar ve sandık mühürü ile cetvel damgalanır.",
        correct: "a",
    },
    {
        question: "Bedeni hiçbir engeli (görme engelli / felçli / elleri eksik olan vb. gibi) bulunmayan bir seçmenin yanında gelen yakını zihinsel engelli olduğunu belirtilirse, oyunu kullanırken sandık kurulundan birinin veya müşahitlerin yardımıyla oy kullanmasına izin verilebilir.",
        a: "DOĞRU",
        b: "YANLIŞ",
        correct: "b",
    },
    {
        question: "Seçim çevresinde aşağıdakilerden hangisi seçmenler tarafından bulundurulabilir?",
        a: "Silah",
        b: "Üniforma",
        c: "Siyasi Parti Amblemi içeren malzemeler",
        d: "Resmi belgeler",
        correct: "d",
    },
    {
        question: "Oy verme süresi ne zaman başlar ve biter?",
        a: "Doğu illerde 08:00-17:00, Batı illerde 09:00-18:00",
        b: "Tüm illerde 08:30-17:30",
        c: "Tüm illerde 08:00-17:00",
        d: "Doğu illerde 07:00-16:00, Batı İllerde 08:00-17:00",
        correct: "c",
    },
    {
        question: "Sandık kurulu yemin ettikten sonra gelen sandık kurulu üyesi, en kısa zamanda yemin edip yerine geçen üyeden görevini devralır.",
        a: "DOĞRU",
        b: "YANLIŞ",
        correct: "b",
    },
    {
        question: "Aşağıdakilerden hangisi doğrudur?",
        a: "Sayım işlemleri sırasında zarflar, sandık görevlileri tarafından toplu şekilde açılarak okunur.",
        b: "Önce CB seçimine ait pusulaların sayım ve dökümü yapılır.",
        c: "Zarftan çıkan pusulalar önce mühürlü yüzleri görünecek şekilde tasnif edilir.",
        d: "Sandıklar, sayım ve döküm işlemleri bitmeden oy verme alanından çıkarılıp daha geniş ve rahat bir alana götürülebilir.",
        correct: "b",
    },
    {
        question: "Kimler oy kullanabilir?",
        a: "Türkçe bilmeyen bireyler",
        b: "Başka ülke vatandaşları",
        c: "Askeri öğrenciler",
        d: "Seçmen listesinde adı ve TC kimlik numarası bulunan tüm bireyler",
        correct: "d",
    },
    {
        question: "Tamamı yırtılmış ve kopartılmış olsa da o oy pusulası geçerlidir?",
        a: "Doğru",
        b: "Yanlış",
        correct: "b",
    },
    {
        question: "Sandık kurulu başkanı, seçimden önceki gün oy pusulası torbasını teslim alarak işlemleri kolaylaştırmak adına mühürleme yapabilir.",
        a: "Doğru",
        b: "Yanlış",
        correct: "b",
    },
];